"use client";

import { useEffect, useMemo, useState } from "react";

type Employer = {
  id: number; name: string; company: string | null; branches: string | null; status: string;
  email: string | null; contactNumber: string | null; branchStatus: string; president: string | null;
  longAddress: string | null; shortAddress: string | null; logo: string | null; secDti: string | null;
  tin: string | null; sss: string | null; hdmf: string | null; phic: string | null; _count: { employees: number };
};

const emptyForm = { name: "", tradeName: "", status: "Active", email: "", contactNumber: "", branchName: "", branchStatus: "Open", president: "", longAddress: "", shortAddress: "", logo: "", secDti: "", tin: "", sss: "", hdmf: "", phic: "" };
const formatNumber = (value: string, groups: number[]) => {
  const digits = value.replace(/\D/g, "").slice(0, groups.reduce((a, b) => a + b, 0)); let offset = 0;
  return groups.map((size) => { const part = digits.slice(offset, offset + size); offset += size; return part; }).filter(Boolean).join("-");
};
const contact = (value: string) => { const digits = value.replace(/\D/g, "").slice(0, 10); return [digits.slice(0, 2), digits.slice(2, 6), digits.slice(6, 10)].filter(Boolean).join(" "); };

export default function EmployersPage() {
  const [employers, setEmployers] = useState<Employer[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<Employer | null>(null); const [openMenu, setOpenMenu] = useState<number | null>(null); const [modalOpen, setModalOpen] = useState(false); const [saving, setSaving] = useState(false);
  const load = () => fetch("/api/employers").then(async (r) => { const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to load employers"); setEmployers(d.employers); }).catch((e: Error) => setMessage(e.message));
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return employers.filter((e) => !q || [e.name, e.company, e.branches, e.email].some((v) => v?.toLowerCase().includes(q))); }, [employers, query]);
  const openForm = (employer?: Employer) => {
    setEditing(employer || null); setForm(employer ? { name: employer.name, tradeName: employer.company || "", status: employer.status, email: employer.email || "", contactNumber: employer.contactNumber || "", branchName: employer.branches || "", branchStatus: employer.branchStatus, president: employer.president || "", longAddress: employer.longAddress || "", shortAddress: employer.shortAddress || "", logo: employer.logo || "", secDti: employer.secDti || "", tin: employer.tin || "", sss: employer.sss || "", hdmf: employer.hdmf || "", phic: employer.phic || "" } : { ...emptyForm }); setModalOpen(true);
  };
  const update = (key: keyof typeof emptyForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await fetch(editing ? `/api/employers/${editing.id}` : "/api/employers", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to save employer"); setForm(emptyForm); setEditing(null); setModalOpen(false); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save employer"); } finally { setSaving(false); } };
  const field = (label: string, key: keyof typeof emptyForm, type = "text") => <label className="grid gap-1 text-sm font-medium text-gray-700"><span>{label}</span><input type={type} value={form[key]} onChange={(e) => update(key, e.target.value)} className="rounded-lg border border-gray-300 px-3 py-2 text-gray-900" /></label>;
  return <main className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-blue-600">HRDB-Lenard</p><h1 className="mt-1 text-3xl font-bold text-gray-900">Employers</h1><p className="mt-2 text-gray-600">Manage employer, branch, and government information.</p></div><button type="button" onClick={() => openForm()} className="rounded-lg bg-[#172554] px-4 py-2 text-sm font-semibold text-white">Add employer</button></header>
    <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search employers..." className="mb-6 w-full rounded-lg border border-gray-300 bg-white p-3 text-gray-900" />{message && <p className="mb-4 text-red-600">{message}</p>}
    <div className="grid gap-4 md:grid-cols-2">{filtered.map((employer) => <article key={employer.id} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div className="flex gap-3">{employer.logo ? <img src={employer.logo} alt="" className="h-14 w-14 rounded-lg object-cover" /> : <div className="flex h-14 w-14 items-center justify-center rounded-lg bg-gray-100 text-xs text-gray-400">Logo</div>}<div><h2 className="font-semibold text-gray-900">{employer.name}</h2><p className="text-sm text-gray-600">{employer.company || "No trade name"}</p></div></div><div className="relative"><button type="button" onClick={() => setOpenMenu(openMenu === employer.id ? null : employer.id)} className="text-xl text-gray-400">•••</button>{openMenu === employer.id && <button type="button" onClick={() => { openForm(employer); setOpenMenu(null); }} className="absolute right-0 top-7 z-10 rounded border bg-white px-3 py-2 text-sm text-gray-700 shadow">Update</button>}</div></div><div className="mt-4 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><p><span className="text-gray-500">Status</span><br />{employer.status}</p><p><span className="text-gray-500">Branch</span><br />{employer.branches || "Not set"}</p><p><span className="text-gray-500">Contact</span><br />{employer.contactNumber || "Not set"}</p><p><span className="text-gray-500">Employees</span><br />{employer._count.employees}</p></div></article>)}</div>
    {modalOpen && <div className="fixed inset-0 z-30 flex items-center justify-center overflow-y-auto bg-black/40 p-4"><form onSubmit={submit} className="w-full max-w-3xl rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{editing ? "Update employer" : "Add employer"}</h2><button type="button" onClick={() => { setEditing(null); setForm(emptyForm); setModalOpen(false); }} className="text-2xl text-gray-400">×</button></div><div className="grid gap-4 sm:grid-cols-2">{field("Employer Name", "name")}{field("Trade Name", "tradeName")}<label className="grid gap-1 text-sm font-medium text-gray-700"><span>Status</span><select value={form.status} onChange={(e) => update("status", e.target.value)} className="rounded-lg border border-gray-300 px-3 py-2 text-gray-900"><option>Active</option><option>Inactive</option></select></label>{field("Email Address", "email", "email")}<label className="grid gap-1 text-sm font-medium text-gray-700"><span>Contact Number</span><input value={form.contactNumber} onChange={(e) => update("contactNumber", contact(e.target.value))} placeholder="00 0000 0000" className="rounded-lg border border-gray-300 px-3 py-2 text-gray-900" /></label>{field("Branch Name", "branchName")}<label className="grid gap-1 text-sm font-medium text-gray-700"><span>Branch Status</span><select value={form.branchStatus} onChange={(e) => update("branchStatus", e.target.value)} className="rounded-lg border border-gray-300 px-3 py-2 text-gray-900"><option>Open</option><option>Close</option></select></label>{field("President", "president")} {field("Long Address", "longAddress")} {field("Short Address", "shortAddress")} {field("Logo", "logo")}<h3 className="border-b pb-2 text-base font-semibold sm:col-span-2">Government Agencies</h3>{field("SEC / DTI", "secDti")}{field("TIN", "tin")}{field("SSS", "sss")}{field("HDMF", "hdmf")}{field("PHIC", "phic")}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => { setEditing(null); setForm(emptyForm); setModalOpen(false); }} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={saving} className="rounded-lg bg-[#172554] px-4 py-2 font-semibold text-white">{saving ? "Saving..." : "Save employer"}</button></div></form></div>}</div></main>;
}
